[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diskinfo"
description = "A disk information Python library for Linux"
readme = "README.md"
version = "0.9.2"
authors = [
    { name = "Peter Sulyok", email = "peter@sulyok.net" }
]
requires-python = ">=3.6"
keywords = ["disk", "linux"]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Hardware",
    "Development Status :: 4 - Beta"
]

[project.urls]
"Homepage" = "https://github.com/petersulyok/disk_info"
"Documentation" = "https://disk-info.readthedocs.io/en/latest/index.html"
